### ISSUE TITLE
Decide priorities for sections currently staked out

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s-developer#1]
First draft, so much will change, but figuring out a sense of priorities, and whether the basic sections here need immediate adjustment should happen quickly. Any thoughts from @zerocrates @jimsafley @kalbers @kimisgold appreciated

**Comment by zerocrates** [comment]
I think we probably want to have a separate section for pages which will basically be lists of things: events, configuration keys, etc. I see you've got some pages for some of that stuff, but it's kind of interspersed with more tutorial-y content it seems to me. I'd expect to find that kind of reference info in an easily-accessible separate location, particularly since the PHP API reference will already be separate by necessity.

**Comment by patrickmj** [comment]
Makes sense. My first thought about the overall heading for that is 'Glossaries', e.g. 'Glossary of events', 'Glossary of configuration keys', etc., but that sounds to me like it might be my academia background asserting itself. Thoughts on a better catch-all term for the top-level navigation?

**Comment by jimsafley** [comment]
Our users will understand "Glossary of events" or "List of events" or simply "Events". Call it whatever you want. We can change it later, correct?

**Comment by patrickmj** [comment]
Yep. Easily changeable. I'll start with "Glossaries" as the top level, then, and see what it looks like.

**Comment by zerocrates** [comment]
We talked briefly in person, but I'll register my preference for "Reference" as the section name.
